apiVersion: v2
name: media-operator-requests
description: Kubernetes operator for declarative media request manager (Seerr/Jellyseerr) configuration
type: application
version: 0.1.0
appVersion: "0.1.0"
