//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppConnection) DeepCopyInto(out *AppConnection) {
	*out = *in
	out.APIKeySecretRef = in.APIKeySecretRef
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConnection.
func (in *AppConnection) DeepCopy() *AppConnection {
	if in == nil {
		return nil
	}
	out := new(AppConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigField) DeepCopyInto(out *ConfigField) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(FieldValue)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigField.
func (in *ConfigField) DeepCopy() *ConfigField {
	if in == nil {
		return nil
	}
	out := new(ConfigField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomFormat) DeepCopyInto(out *CustomFormat) {
	*out = *in
	if in.IncludeCustomFormatWhenRenaming != nil {
		in, out := &in.IncludeCustomFormatWhenRenaming, &out.IncludeCustomFormatWhenRenaming
		*out = new(bool)
		**out = **in
	}
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = make([]CustomFormatSpecification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomFormat.
func (in *CustomFormat) DeepCopy() *CustomFormat {
	if in == nil {
		return nil
	}
	out := new(CustomFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomFormatSpecification) DeepCopyInto(out *CustomFormatSpecification) {
	*out = *in
	if in.Negate != nil {
		in, out := &in.Negate, &out.Negate
		*out = new(bool)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]ConfigField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomFormatSpecification.
func (in *CustomFormatSpecification) DeepCopy() *CustomFormatSpecification {
	if in == nil {
		return nil
	}
	out := new(CustomFormatSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadClient) DeepCopyInto(out *DownloadClient) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.UseSsl != nil {
		in, out := &in.UseSsl, &out.UseSsl
		*out = new(bool)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.RemoveCompletedDownloads != nil {
		in, out := &in.RemoveCompletedDownloads, &out.RemoveCompletedDownloads
		*out = new(bool)
		**out = **in
	}
	if in.RemoveFailedDownloads != nil {
		in, out := &in.RemoveFailedDownloads, &out.RemoveFailedDownloads
		*out = new(bool)
		**out = **in
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]ConfigField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadClient.
func (in *DownloadClient) DeepCopy() *DownloadClient {
	if in == nil {
		return nil
	}
	out := new(DownloadClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldValue) DeepCopyInto(out *FieldValue) {
	*out = *in
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldValue.
func (in *FieldValue) DeepCopy() *FieldValue {
	if in == nil {
		return nil
	}
	out := new(FieldValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportList) DeepCopyInto(out *ImportList) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.EnableAutomaticAdd != nil {
		in, out := &in.EnableAutomaticAdd, &out.EnableAutomaticAdd
		*out = new(bool)
		**out = **in
	}
	if in.ShouldMonitor != nil {
		in, out := &in.ShouldMonitor, &out.ShouldMonitor
		*out = new(bool)
		**out = **in
	}
	if in.SeasonFolder != nil {
		in, out := &in.SeasonFolder, &out.SeasonFolder
		*out = new(bool)
		**out = **in
	}
	if in.SearchOnAdd != nil {
		in, out := &in.SearchOnAdd, &out.SearchOnAdd
		*out = new(bool)
		**out = **in
	}
	if in.ListOrder != nil {
		in, out := &in.ListOrder, &out.ListOrder
		*out = new(int)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]ConfigField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportList.
func (in *ImportList) DeepCopy() *ImportList {
	if in == nil {
		return nil
	}
	out := new(ImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Indexer) DeepCopyInto(out *Indexer) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.EnableRss != nil {
		in, out := &in.EnableRss, &out.EnableRss
		*out = new(bool)
		**out = **in
	}
	if in.EnableAutomaticSearch != nil {
		in, out := &in.EnableAutomaticSearch, &out.EnableAutomaticSearch
		*out = new(bool)
		**out = **in
	}
	if in.EnableInteractiveSearch != nil {
		in, out := &in.EnableInteractiveSearch, &out.EnableInteractiveSearch
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]ConfigField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Indexer.
func (in *Indexer) DeepCopy() *Indexer {
	if in == nil {
		return nil
	}
	out := new(Indexer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Notification) DeepCopyInto(out *Notification) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]ConfigField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnGrab != nil {
		in, out := &in.OnGrab, &out.OnGrab
		*out = new(bool)
		**out = **in
	}
	if in.OnDownload != nil {
		in, out := &in.OnDownload, &out.OnDownload
		*out = new(bool)
		**out = **in
	}
	if in.OnUpgrade != nil {
		in, out := &in.OnUpgrade, &out.OnUpgrade
		*out = new(bool)
		**out = **in
	}
	if in.OnRename != nil {
		in, out := &in.OnRename, &out.OnRename
		*out = new(bool)
		**out = **in
	}
	if in.OnHealthIssue != nil {
		in, out := &in.OnHealthIssue, &out.OnHealthIssue
		*out = new(bool)
		**out = **in
	}
	if in.OnHealthRestored != nil {
		in, out := &in.OnHealthRestored, &out.OnHealthRestored
		*out = new(bool)
		**out = **in
	}
	if in.OnApplicationUpdate != nil {
		in, out := &in.OnApplicationUpdate, &out.OnApplicationUpdate
		*out = new(bool)
		**out = **in
	}
	if in.OnManualInteractionRequired != nil {
		in, out := &in.OnManualInteractionRequired, &out.OnManualInteractionRequired
		*out = new(bool)
		**out = **in
	}
	if in.IncludeHealthWarnings != nil {
		in, out := &in.IncludeHealthWarnings, &out.IncludeHealthWarnings
		*out = new(bool)
		**out = **in
	}
	if in.OnSeriesAdd != nil {
		in, out := &in.OnSeriesAdd, &out.OnSeriesAdd
		*out = new(bool)
		**out = **in
	}
	if in.OnSeriesDelete != nil {
		in, out := &in.OnSeriesDelete, &out.OnSeriesDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnEpisodeFileDelete != nil {
		in, out := &in.OnEpisodeFileDelete, &out.OnEpisodeFileDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnEpisodeFileDeleteForUpgrade != nil {
		in, out := &in.OnEpisodeFileDeleteForUpgrade, &out.OnEpisodeFileDeleteForUpgrade
		*out = new(bool)
		**out = **in
	}
	if in.OnMovieAdded != nil {
		in, out := &in.OnMovieAdded, &out.OnMovieAdded
		*out = new(bool)
		**out = **in
	}
	if in.OnMovieDelete != nil {
		in, out := &in.OnMovieDelete, &out.OnMovieDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnMovieFileDelete != nil {
		in, out := &in.OnMovieFileDelete, &out.OnMovieFileDelete
		*out = new(bool)
		**out = **in
	}
	if in.OnMovieFileDeleteForUpgrade != nil {
		in, out := &in.OnMovieFileDeleteForUpgrade, &out.OnMovieFileDeleteForUpgrade
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Notification.
func (in *Notification) DeepCopy() *Notification {
	if in == nil {
		return nil
	}
	out := new(Notification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfile) DeepCopyInto(out *QualityProfile) {
	*out = *in
	if in.UpgradeAllowed != nil {
		in, out := &in.UpgradeAllowed, &out.UpgradeAllowed
		*out = new(bool)
		**out = **in
	}
	if in.MinFormatScore != nil {
		in, out := &in.MinFormatScore, &out.MinFormatScore
		*out = new(int)
		**out = **in
	}
	if in.CutoffFormatScore != nil {
		in, out := &in.CutoffFormatScore, &out.CutoffFormatScore
		*out = new(int)
		**out = **in
	}
	if in.MinUpgradeFormatScore != nil {
		in, out := &in.MinUpgradeFormatScore, &out.MinUpgradeFormatScore
		*out = new(int)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QualityProfileItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FormatItems != nil {
		in, out := &in.FormatItems, &out.FormatItems
		*out = make([]QualityProfileFormatItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfile.
func (in *QualityProfile) DeepCopy() *QualityProfile {
	if in == nil {
		return nil
	}
	out := new(QualityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileFormatItem) DeepCopyInto(out *QualityProfileFormatItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileFormatItem.
func (in *QualityProfileFormatItem) DeepCopy() *QualityProfileFormatItem {
	if in == nil {
		return nil
	}
	out := new(QualityProfileFormatItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileGroupItem) DeepCopyInto(out *QualityProfileGroupItem) {
	*out = *in
	out.Quality = in.Quality
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileGroupItem.
func (in *QualityProfileGroupItem) DeepCopy() *QualityProfileGroupItem {
	if in == nil {
		return nil
	}
	out := new(QualityProfileGroupItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileItem) DeepCopyInto(out *QualityProfileItem) {
	*out = *in
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(QualityReference)
		**out = **in
	}
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = new(bool)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QualityProfileGroupItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileItem.
func (in *QualityProfileItem) DeepCopy() *QualityProfileItem {
	if in == nil {
		return nil
	}
	out := new(QualityProfileItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityReference) DeepCopyInto(out *QualityReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityReference.
func (in *QualityReference) DeepCopy() *QualityReference {
	if in == nil {
		return nil
	}
	out := new(QualityReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconcileConfig) DeepCopyInto(out *ReconcileConfig) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Prune != nil {
		in, out := &in.Prune, &out.Prune
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconcileConfig.
func (in *ReconcileConfig) DeepCopy() *ReconcileConfig {
	if in == nil {
		return nil
	}
	out := new(ReconcileConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootFolder) DeepCopyInto(out *RootFolder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootFolder.
func (in *RootFolder) DeepCopy() *RootFolder {
	if in == nil {
		return nil
	}
	out := new(RootFolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}
