version: 2

builds:
  - id: media-operator-pvr
    main: ./cmd/pvr
    binary: media-operator-pvr
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]
  - id: media-operator-indexers
    main: ./cmd/indexers
    binary: media-operator-indexers
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]
  - id: media-operator-subtitles
    main: ./cmd/subtitles
    binary: media-operator-subtitles
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]
  - id: media-operator-curation
    main: ./cmd/curation
    binary: media-operator-curation
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]
  - id: media-operator-downloads
    main: ./cmd/downloads
    binary: media-operator-downloads
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]
  - id: media-operator-mediaservers
    main: ./cmd/mediaservers
    binary: media-operator-mediaservers
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]
  - id: media-operator-requests
    main: ./cmd/requests
    binary: media-operator-requests
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]
  - id: media-operator-transcode
    main: ./cmd/transcode
    binary: media-operator-transcode
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]
  - id: media-operator-automation
    main: ./cmd/automation
    binary: media-operator-automation
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"]

dockers:
  - image_templates: ["ghcr.io/kyleseneker/media-operator-pvr:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-pvr"]
    goarch: amd64
    ids: [media-operator-pvr]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-pvr:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-pvr"]
    goarch: arm64
    ids: [media-operator-pvr]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-indexers:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-indexers"]
    goarch: amd64
    ids: [media-operator-indexers]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-indexers:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-indexers"]
    goarch: arm64
    ids: [media-operator-indexers]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-subtitles:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-subtitles"]
    goarch: amd64
    ids: [media-operator-subtitles]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-subtitles:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-subtitles"]
    goarch: arm64
    ids: [media-operator-subtitles]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-curation:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-curation"]
    goarch: amd64
    ids: [media-operator-curation]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-curation:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-curation"]
    goarch: arm64
    ids: [media-operator-curation]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-downloads:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-downloads"]
    goarch: amd64
    ids: [media-operator-downloads]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-downloads:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-downloads"]
    goarch: arm64
    ids: [media-operator-downloads]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-mediaservers:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-mediaservers"]
    goarch: amd64
    ids: [media-operator-mediaservers]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-mediaservers:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-mediaservers"]
    goarch: arm64
    ids: [media-operator-mediaservers]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-requests:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-requests"]
    goarch: amd64
    ids: [media-operator-requests]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-requests:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-requests"]
    goarch: arm64
    ids: [media-operator-requests]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-transcode:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-transcode"]
    goarch: amd64
    ids: [media-operator-transcode]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-transcode:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-transcode"]
    goarch: arm64
    ids: [media-operator-transcode]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-automation:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--build-arg=BINARY=media-operator-automation"]
    goarch: amd64
    ids: [media-operator-automation]
  - image_templates: ["ghcr.io/kyleseneker/media-operator-automation:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--build-arg=BINARY=media-operator-automation"]
    goarch: arm64
    ids: [media-operator-automation]

docker_manifests:
  - name_template: "ghcr.io/kyleseneker/media-operator-pvr:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-pvr:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-pvr:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-pvr:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-pvr:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-pvr:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-indexers:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-indexers:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-indexers:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-indexers:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-indexers:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-indexers:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-subtitles:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-subtitles:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-subtitles:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-subtitles:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-subtitles:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-subtitles:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-curation:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-curation:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-curation:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-curation:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-curation:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-curation:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-downloads:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-downloads:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-downloads:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-downloads:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-downloads:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-downloads:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-mediaservers:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-mediaservers:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-mediaservers:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-mediaservers:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-mediaservers:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-mediaservers:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-requests:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-requests:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-requests:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-requests:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-requests:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-requests:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-transcode:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-transcode:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-transcode:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-transcode:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-transcode:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-transcode:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-automation:{{ .Version }}"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-automation:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-automation:{{ .Version }}-arm64"
  - name_template: "ghcr.io/kyleseneker/media-operator-automation:latest"
    image_templates:
      - "ghcr.io/kyleseneker/media-operator-automation:{{ .Version }}-amd64"
      - "ghcr.io/kyleseneker/media-operator-automation:{{ .Version }}-arm64"

archives:
  - formats: ['tar.gz']

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  extra_files:
    - glob: config/crd/bases/*.yaml
