---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - media-operator.dev
  resources:
  - autobrrconfigs
  - bazarrconfigs
  - flaresolverrconfigs
  - jellyfinconfigs
  - lidarrconfigs
  - maintainerrconfigs
  - plexconfigs
  - prowlarrconfigs
  - qbittorrentconfigs
  - radarrconfigs
  - readarrconfigs
  - sabnzbdconfigs
  - seerrconfigs
  - sonarrconfigs
  - tdarrconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - media-operator.dev
  resources:
  - autobrrconfigs/status
  - bazarrconfigs/status
  - flaresolverrconfigs/status
  - jellyfinconfigs/status
  - lidarrconfigs/status
  - maintainerrconfigs/status
  - plexconfigs/status
  - prowlarrconfigs/status
  - qbittorrentconfigs/status
  - radarrconfigs/status
  - readarrconfigs/status
  - sabnzbdconfigs/status
  - seerrconfigs/status
  - sonarrconfigs/status
  - tdarrconfigs/status
  verbs:
  - get
  - patch
  - update
