apiVersion: media-operator.dev/v1alpha1
kind: FlareSolverrConfig
metadata:
  name: flaresolverr
  namespace: media
  labels:
    app.kubernetes.io/name: media-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  connection:
    url: http://flaresolverr:8191
  sessions:
    - name: prowlarr
