//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kyleseneker/media-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QBittorrentCategory) DeepCopyInto(out *QBittorrentCategory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QBittorrentCategory.
func (in *QBittorrentCategory) DeepCopy() *QBittorrentCategory {
	if in == nil {
		return nil
	}
	out := new(QBittorrentCategory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QBittorrentConfig) DeepCopyInto(out *QBittorrentConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QBittorrentConfig.
func (in *QBittorrentConfig) DeepCopy() *QBittorrentConfig {
	if in == nil {
		return nil
	}
	out := new(QBittorrentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QBittorrentConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QBittorrentConfigList) DeepCopyInto(out *QBittorrentConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QBittorrentConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QBittorrentConfigList.
func (in *QBittorrentConfigList) DeepCopy() *QBittorrentConfigList {
	if in == nil {
		return nil
	}
	out := new(QBittorrentConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QBittorrentConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QBittorrentConfigSpec) DeepCopyInto(out *QBittorrentConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Preferences != nil {
		in, out := &in.Preferences, &out.Preferences
		*out = new(QBittorrentPreferences)
		(*in).DeepCopyInto(*out)
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]QBittorrentCategory, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QBittorrentConfigSpec.
func (in *QBittorrentConfigSpec) DeepCopy() *QBittorrentConfigSpec {
	if in == nil {
		return nil
	}
	out := new(QBittorrentConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QBittorrentConfigStatus) DeepCopyInto(out *QBittorrentConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QBittorrentConfigStatus.
func (in *QBittorrentConfigStatus) DeepCopy() *QBittorrentConfigStatus {
	if in == nil {
		return nil
	}
	out := new(QBittorrentConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QBittorrentConnection) DeepCopyInto(out *QBittorrentConnection) {
	*out = *in
	out.UsernameSecretRef = in.UsernameSecretRef
	out.PasswordSecretRef = in.PasswordSecretRef
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(commonv1alpha1.TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QBittorrentConnection.
func (in *QBittorrentConnection) DeepCopy() *QBittorrentConnection {
	if in == nil {
		return nil
	}
	out := new(QBittorrentConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QBittorrentPreferences) DeepCopyInto(out *QBittorrentPreferences) {
	*out = *in
	if in.TempPathEnabled != nil {
		in, out := &in.TempPathEnabled, &out.TempPathEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DHT != nil {
		in, out := &in.DHT, &out.DHT
		*out = new(bool)
		**out = **in
	}
	if in.PEX != nil {
		in, out := &in.PEX, &out.PEX
		*out = new(bool)
		**out = **in
	}
	if in.LSD != nil {
		in, out := &in.LSD, &out.LSD
		*out = new(bool)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(int)
		**out = **in
	}
	if in.MaxConnec != nil {
		in, out := &in.MaxConnec, &out.MaxConnec
		*out = new(int)
		**out = **in
	}
	if in.MaxConnecPerTorrent != nil {
		in, out := &in.MaxConnecPerTorrent, &out.MaxConnecPerTorrent
		*out = new(int)
		**out = **in
	}
	if in.MaxUploads != nil {
		in, out := &in.MaxUploads, &out.MaxUploads
		*out = new(int)
		**out = **in
	}
	if in.MaxUploadsPerTorrent != nil {
		in, out := &in.MaxUploadsPerTorrent, &out.MaxUploadsPerTorrent
		*out = new(int)
		**out = **in
	}
	if in.MaxRatioEnabled != nil {
		in, out := &in.MaxRatioEnabled, &out.MaxRatioEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxRatio != nil {
		in, out := &in.MaxRatio, &out.MaxRatio
		*out = new(string)
		**out = **in
	}
	if in.MaxSeedingTimeEnabled != nil {
		in, out := &in.MaxSeedingTimeEnabled, &out.MaxSeedingTimeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxSeedingTime != nil {
		in, out := &in.MaxSeedingTime, &out.MaxSeedingTime
		*out = new(int)
		**out = **in
	}
	if in.PreallocateAll != nil {
		in, out := &in.PreallocateAll, &out.PreallocateAll
		*out = new(bool)
		**out = **in
	}
	if in.WebUIPort != nil {
		in, out := &in.WebUIPort, &out.WebUIPort
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QBittorrentPreferences.
func (in *QBittorrentPreferences) DeepCopy() *QBittorrentPreferences {
	if in == nil {
		return nil
	}
	out := new(QBittorrentPreferences)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SabnzbdCategory) DeepCopyInto(out *SabnzbdCategory) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SabnzbdCategory.
func (in *SabnzbdCategory) DeepCopy() *SabnzbdCategory {
	if in == nil {
		return nil
	}
	out := new(SabnzbdCategory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SabnzbdConfig) DeepCopyInto(out *SabnzbdConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SabnzbdConfig.
func (in *SabnzbdConfig) DeepCopy() *SabnzbdConfig {
	if in == nil {
		return nil
	}
	out := new(SabnzbdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SabnzbdConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SabnzbdConfigList) DeepCopyInto(out *SabnzbdConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SabnzbdConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SabnzbdConfigList.
func (in *SabnzbdConfigList) DeepCopy() *SabnzbdConfigList {
	if in == nil {
		return nil
	}
	out := new(SabnzbdConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SabnzbdConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SabnzbdConfigSpec) DeepCopyInto(out *SabnzbdConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.General != nil {
		in, out := &in.General, &out.General
		*out = new(SabnzbdGeneral)
		(*in).DeepCopyInto(*out)
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]SabnzbdServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]SabnzbdCategory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Folders != nil {
		in, out := &in.Folders, &out.Folders
		*out = new(SabnzbdFolders)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SabnzbdConfigSpec.
func (in *SabnzbdConfigSpec) DeepCopy() *SabnzbdConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SabnzbdConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SabnzbdConfigStatus) DeepCopyInto(out *SabnzbdConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SabnzbdConfigStatus.
func (in *SabnzbdConfigStatus) DeepCopy() *SabnzbdConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SabnzbdConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SabnzbdFolders) DeepCopyInto(out *SabnzbdFolders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SabnzbdFolders.
func (in *SabnzbdFolders) DeepCopy() *SabnzbdFolders {
	if in == nil {
		return nil
	}
	out := new(SabnzbdFolders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SabnzbdGeneral) DeepCopyInto(out *SabnzbdGeneral) {
	*out = *in
	if in.PauseOnPostProcessing != nil {
		in, out := &in.PauseOnPostProcessing, &out.PauseOnPostProcessing
		*out = new(bool)
		**out = **in
	}
	if in.AutoSort != nil {
		in, out := &in.AutoSort, &out.AutoSort
		*out = new(bool)
		**out = **in
	}
	if in.PreCheck != nil {
		in, out := &in.PreCheck, &out.PreCheck
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SabnzbdGeneral.
func (in *SabnzbdGeneral) DeepCopy() *SabnzbdGeneral {
	if in == nil {
		return nil
	}
	out := new(SabnzbdGeneral)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SabnzbdServer) DeepCopyInto(out *SabnzbdServer) {
	*out = *in
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = new(int)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(int)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SabnzbdServer.
func (in *SabnzbdServer) DeepCopy() *SabnzbdServer {
	if in == nil {
		return nil
	}
	out := new(SabnzbdServer)
	in.DeepCopyInto(out)
	return out
}
