//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kyleseneker/media-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrArrConnection) DeepCopyInto(out *MaintainerrArrConnection) {
	*out = *in
	out.APIKeySecretRef = in.APIKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrArrConnection.
func (in *MaintainerrArrConnection) DeepCopy() *MaintainerrArrConnection {
	if in == nil {
		return nil
	}
	out := new(MaintainerrArrConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrConfig) DeepCopyInto(out *MaintainerrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrConfig.
func (in *MaintainerrConfig) DeepCopy() *MaintainerrConfig {
	if in == nil {
		return nil
	}
	out := new(MaintainerrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintainerrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrConfigList) DeepCopyInto(out *MaintainerrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaintainerrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrConfigList.
func (in *MaintainerrConfigList) DeepCopy() *MaintainerrConfigList {
	if in == nil {
		return nil
	}
	out := new(MaintainerrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintainerrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrConfigSpec) DeepCopyInto(out *MaintainerrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PlexConnection != nil {
		in, out := &in.PlexConnection, &out.PlexConnection
		*out = new(MaintainerrPlexConnection)
		**out = **in
	}
	if in.SonarrConnection != nil {
		in, out := &in.SonarrConnection, &out.SonarrConnection
		*out = new(MaintainerrArrConnection)
		**out = **in
	}
	if in.RadarrConnection != nil {
		in, out := &in.RadarrConnection, &out.RadarrConnection
		*out = new(MaintainerrArrConnection)
		**out = **in
	}
	if in.OverseerrConnection != nil {
		in, out := &in.OverseerrConnection, &out.OverseerrConnection
		*out = new(MaintainerrArrConnection)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]MaintainerrRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(MaintainerrSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrConfigSpec.
func (in *MaintainerrConfigSpec) DeepCopy() *MaintainerrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MaintainerrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrConfigStatus) DeepCopyInto(out *MaintainerrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrConfigStatus.
func (in *MaintainerrConfigStatus) DeepCopy() *MaintainerrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(MaintainerrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrPlexConnection) DeepCopyInto(out *MaintainerrPlexConnection) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrPlexConnection.
func (in *MaintainerrPlexConnection) DeepCopy() *MaintainerrPlexConnection {
	if in == nil {
		return nil
	}
	out := new(MaintainerrPlexConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrRule) DeepCopyInto(out *MaintainerrRule) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.DeleteFromDisk != nil {
		in, out := &in.DeleteFromDisk, &out.DeleteFromDisk
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MaintainerrRuleCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrRule.
func (in *MaintainerrRule) DeepCopy() *MaintainerrRule {
	if in == nil {
		return nil
	}
	out := new(MaintainerrRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrRuleCondition) DeepCopyInto(out *MaintainerrRuleCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrRuleCondition.
func (in *MaintainerrRuleCondition) DeepCopy() *MaintainerrRuleCondition {
	if in == nil {
		return nil
	}
	out := new(MaintainerrRuleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintainerrSettings) DeepCopyInto(out *MaintainerrSettings) {
	*out = *in
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintainerrSettings.
func (in *MaintainerrSettings) DeepCopy() *MaintainerrSettings {
	if in == nil {
		return nil
	}
	out := new(MaintainerrSettings)
	in.DeepCopyInto(out)
	return out
}
