//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kyleseneker/media-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdarrConfig) DeepCopyInto(out *TdarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdarrConfig.
func (in *TdarrConfig) DeepCopy() *TdarrConfig {
	if in == nil {
		return nil
	}
	out := new(TdarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TdarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdarrConfigList) DeepCopyInto(out *TdarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TdarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdarrConfigList.
func (in *TdarrConfigList) DeepCopy() *TdarrConfigList {
	if in == nil {
		return nil
	}
	out := new(TdarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TdarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdarrConfigSpec) DeepCopyInto(out *TdarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Libraries != nil {
		in, out := &in.Libraries, &out.Libraries
		*out = make([]TdarrLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Flows != nil {
		in, out := &in.Flows, &out.Flows
		*out = make([]TdarrFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(TdarrWorkers)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdarrConfigSpec.
func (in *TdarrConfigSpec) DeepCopy() *TdarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TdarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdarrConfigStatus) DeepCopyInto(out *TdarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdarrConfigStatus.
func (in *TdarrConfigStatus) DeepCopy() *TdarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TdarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdarrFlow) DeepCopyInto(out *TdarrFlow) {
	*out = *in
	in.FlowPlugins.DeepCopyInto(&out.FlowPlugins)
	in.FlowEdges.DeepCopyInto(&out.FlowEdges)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdarrFlow.
func (in *TdarrFlow) DeepCopy() *TdarrFlow {
	if in == nil {
		return nil
	}
	out := new(TdarrFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdarrLibrary) DeepCopyInto(out *TdarrLibrary) {
	*out = *in
	if in.FolderWatching != nil {
		in, out := &in.FolderWatching, &out.FolderWatching
		*out = new(bool)
		**out = **in
	}
	if in.ProcessLibrary != nil {
		in, out := &in.ProcessLibrary, &out.ProcessLibrary
		*out = new(bool)
		**out = **in
	}
	if in.ScanOnStart != nil {
		in, out := &in.ScanOnStart, &out.ScanOnStart
		*out = new(bool)
		**out = **in
	}
	if in.ScheduledScanFindNew != nil {
		in, out := &in.ScheduledScanFindNew, &out.ScheduledScanFindNew
		*out = new(bool)
		**out = **in
	}
	if in.ScannerThreadCount != nil {
		in, out := &in.ScannerThreadCount, &out.ScannerThreadCount
		*out = new(int)
		**out = **in
	}
	if in.FFmpeg != nil {
		in, out := &in.FFmpeg, &out.FFmpeg
		*out = new(bool)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdarrLibrary.
func (in *TdarrLibrary) DeepCopy() *TdarrLibrary {
	if in == nil {
		return nil
	}
	out := new(TdarrLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdarrWorkers) DeepCopyInto(out *TdarrWorkers) {
	*out = *in
	if in.TranscodeGPU != nil {
		in, out := &in.TranscodeGPU, &out.TranscodeGPU
		*out = new(int)
		**out = **in
	}
	if in.TranscodeCPU != nil {
		in, out := &in.TranscodeCPU, &out.TranscodeCPU
		*out = new(int)
		**out = **in
	}
	if in.HealthcheckGPU != nil {
		in, out := &in.HealthcheckGPU, &out.HealthcheckGPU
		*out = new(int)
		**out = **in
	}
	if in.HealthcheckCPU != nil {
		in, out := &in.HealthcheckCPU, &out.HealthcheckCPU
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdarrWorkers.
func (in *TdarrWorkers) DeepCopy() *TdarrWorkers {
	if in == nil {
		return nil
	}
	out := new(TdarrWorkers)
	in.DeepCopyInto(out)
	return out
}
