//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kyleseneker/media-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrConfig) DeepCopyInto(out *AutobrrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrConfig.
func (in *AutobrrConfig) DeepCopy() *AutobrrConfig {
	if in == nil {
		return nil
	}
	out := new(AutobrrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutobrrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrConfigList) DeepCopyInto(out *AutobrrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutobrrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrConfigList.
func (in *AutobrrConfigList) DeepCopy() *AutobrrConfigList {
	if in == nil {
		return nil
	}
	out := new(AutobrrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutobrrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrConfigSpec) DeepCopyInto(out *AutobrrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]AutobrrDownloadClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]AutobrrIndexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IRCNetworks != nil {
		in, out := &in.IRCNetworks, &out.IRCNetworks
		*out = make([]AutobrrIRCNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Feeds != nil {
		in, out := &in.Feeds, &out.Feeds
		*out = make([]AutobrrFeed, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]AutobrrFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrConfigSpec.
func (in *AutobrrConfigSpec) DeepCopy() *AutobrrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AutobrrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrConfigStatus) DeepCopyInto(out *AutobrrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrConfigStatus.
func (in *AutobrrConfigStatus) DeepCopy() *AutobrrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AutobrrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrDownloadClient) DeepCopyInto(out *AutobrrDownloadClient) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(AutobrrDownloadClientSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrDownloadClient.
func (in *AutobrrDownloadClient) DeepCopy() *AutobrrDownloadClient {
	if in == nil {
		return nil
	}
	out := new(AutobrrDownloadClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrDownloadClientSettings) DeepCopyInto(out *AutobrrDownloadClientSettings) {
	*out = *in
	if in.PrioritizeProperRepacks != nil {
		in, out := &in.PrioritizeProperRepacks, &out.PrioritizeProperRepacks
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrDownloadClientSettings.
func (in *AutobrrDownloadClientSettings) DeepCopy() *AutobrrDownloadClientSettings {
	if in == nil {
		return nil
	}
	out := new(AutobrrDownloadClientSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrFeed) DeepCopyInto(out *AutobrrFeed) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrFeed.
func (in *AutobrrFeed) DeepCopy() *AutobrrFeed {
	if in == nil {
		return nil
	}
	out := new(AutobrrFeed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrFilter) DeepCopyInto(out *AutobrrFilter) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.Resolutions != nil {
		in, out := &in.Resolutions, &out.Resolutions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Codecs != nil {
		in, out := &in.Codecs, &out.Codecs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(int)
		**out = **in
	}
	if in.UseRegex != nil {
		in, out := &in.UseRegex, &out.UseRegex
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]AutobrrFilterAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrFilter.
func (in *AutobrrFilter) DeepCopy() *AutobrrFilter {
	if in == nil {
		return nil
	}
	out := new(AutobrrFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrFilterAction) DeepCopyInto(out *AutobrrFilterAction) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrFilterAction.
func (in *AutobrrFilterAction) DeepCopy() *AutobrrFilterAction {
	if in == nil {
		return nil
	}
	out := new(AutobrrFilterAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrIRCChannel) DeepCopyInto(out *AutobrrIRCChannel) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrIRCChannel.
func (in *AutobrrIRCChannel) DeepCopy() *AutobrrIRCChannel {
	if in == nil {
		return nil
	}
	out := new(AutobrrIRCChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrIRCNetwork) DeepCopyInto(out *AutobrrIRCNetwork) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
	if in.AuthAccountSecretRef != nil {
		in, out := &in.AuthAccountSecretRef, &out.AuthAccountSecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.AuthPasswordSecretRef != nil {
		in, out := &in.AuthPasswordSecretRef, &out.AuthPasswordSecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]AutobrrIRCChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrIRCNetwork.
func (in *AutobrrIRCNetwork) DeepCopy() *AutobrrIRCNetwork {
	if in == nil {
		return nil
	}
	out := new(AutobrrIRCNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutobrrIndexer) DeepCopyInto(out *AutobrrIndexer) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutobrrIndexer.
func (in *AutobrrIndexer) DeepCopy() *AutobrrIndexer {
	if in == nil {
		return nil
	}
	out := new(AutobrrIndexer)
	in.DeepCopyInto(out)
	return out
}
