//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kyleseneker/media-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinAdminUser) DeepCopyInto(out *JellyfinAdminUser) {
	*out = *in
	out.UsernameSecretRef = in.UsernameSecretRef
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinAdminUser.
func (in *JellyfinAdminUser) DeepCopy() *JellyfinAdminUser {
	if in == nil {
		return nil
	}
	out := new(JellyfinAdminUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinConfig) DeepCopyInto(out *JellyfinConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinConfig.
func (in *JellyfinConfig) DeepCopy() *JellyfinConfig {
	if in == nil {
		return nil
	}
	out := new(JellyfinConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JellyfinConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinConfigList) DeepCopyInto(out *JellyfinConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JellyfinConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinConfigList.
func (in *JellyfinConfigList) DeepCopy() *JellyfinConfigList {
	if in == nil {
		return nil
	}
	out := new(JellyfinConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JellyfinConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinConfigSpec) DeepCopyInto(out *JellyfinConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	out.AdminUser = in.AdminUser
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(JellyfinServer)
		(*in).DeepCopyInto(*out)
	}
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(JellyfinEncoding)
		(*in).DeepCopyInto(*out)
	}
	if in.Libraries != nil {
		in, out := &in.Libraries, &out.Libraries
		*out = make([]JellyfinLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinConfigSpec.
func (in *JellyfinConfigSpec) DeepCopy() *JellyfinConfigSpec {
	if in == nil {
		return nil
	}
	out := new(JellyfinConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinConfigStatus) DeepCopyInto(out *JellyfinConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Initialized != nil {
		in, out := &in.Initialized, &out.Initialized
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinConfigStatus.
func (in *JellyfinConfigStatus) DeepCopy() *JellyfinConfigStatus {
	if in == nil {
		return nil
	}
	out := new(JellyfinConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinConnection) DeepCopyInto(out *JellyfinConnection) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(commonv1alpha1.TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinConnection.
func (in *JellyfinConnection) DeepCopy() *JellyfinConnection {
	if in == nil {
		return nil
	}
	out := new(JellyfinConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinEncoding) DeepCopyInto(out *JellyfinEncoding) {
	*out = *in
	if in.EnableHardwareEncoding != nil {
		in, out := &in.EnableHardwareEncoding, &out.EnableHardwareEncoding
		*out = new(bool)
		**out = **in
	}
	if in.AllowHevcEncoding != nil {
		in, out := &in.AllowHevcEncoding, &out.AllowHevcEncoding
		*out = new(bool)
		**out = **in
	}
	if in.EnableTonemapping != nil {
		in, out := &in.EnableTonemapping, &out.EnableTonemapping
		*out = new(bool)
		**out = **in
	}
	if in.EnableVppTonemapping != nil {
		in, out := &in.EnableVppTonemapping, &out.EnableVppTonemapping
		*out = new(bool)
		**out = **in
	}
	if in.H264Crf != nil {
		in, out := &in.H264Crf, &out.H264Crf
		*out = new(int)
		**out = **in
	}
	if in.H265Crf != nil {
		in, out := &in.H265Crf, &out.H265Crf
		*out = new(int)
		**out = **in
	}
	if in.HardwareDecodingCodecs != nil {
		in, out := &in.HardwareDecodingCodecs, &out.HardwareDecodingCodecs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableIntelLowPowerH264HwEncoder != nil {
		in, out := &in.EnableIntelLowPowerH264HwEncoder, &out.EnableIntelLowPowerH264HwEncoder
		*out = new(bool)
		**out = **in
	}
	if in.EnableIntelLowPowerHevcHwEncoder != nil {
		in, out := &in.EnableIntelLowPowerHevcHwEncoder, &out.EnableIntelLowPowerHevcHwEncoder
		*out = new(bool)
		**out = **in
	}
	if in.EnableSubtitleExtraction != nil {
		in, out := &in.EnableSubtitleExtraction, &out.EnableSubtitleExtraction
		*out = new(bool)
		**out = **in
	}
	if in.EnableThrottling != nil {
		in, out := &in.EnableThrottling, &out.EnableThrottling
		*out = new(bool)
		**out = **in
	}
	if in.ThrottleDelaySeconds != nil {
		in, out := &in.ThrottleDelaySeconds, &out.ThrottleDelaySeconds
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinEncoding.
func (in *JellyfinEncoding) DeepCopy() *JellyfinEncoding {
	if in == nil {
		return nil
	}
	out := new(JellyfinEncoding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinLibrary) DeepCopyInto(out *JellyfinLibrary) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableRealtimeMonitor != nil {
		in, out := &in.EnableRealtimeMonitor, &out.EnableRealtimeMonitor
		*out = new(bool)
		**out = **in
	}
	if in.EnableTrickplayImageExtraction != nil {
		in, out := &in.EnableTrickplayImageExtraction, &out.EnableTrickplayImageExtraction
		*out = new(bool)
		**out = **in
	}
	if in.AutomaticRefreshIntervalDays != nil {
		in, out := &in.AutomaticRefreshIntervalDays, &out.AutomaticRefreshIntervalDays
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinLibrary.
func (in *JellyfinLibrary) DeepCopy() *JellyfinLibrary {
	if in == nil {
		return nil
	}
	out := new(JellyfinLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinServer) DeepCopyInto(out *JellyfinServer) {
	*out = *in
	if in.LogFileRetentionDays != nil {
		in, out := &in.LogFileRetentionDays, &out.LogFileRetentionDays
		*out = new(int)
		**out = **in
	}
	if in.EnableGroupingMoviesIntoCollections != nil {
		in, out := &in.EnableGroupingMoviesIntoCollections, &out.EnableGroupingMoviesIntoCollections
		*out = new(bool)
		**out = **in
	}
	if in.DisplaySpecialsWithinSeasons != nil {
		in, out := &in.DisplaySpecialsWithinSeasons, &out.DisplaySpecialsWithinSeasons
		*out = new(bool)
		**out = **in
	}
	if in.LibraryMonitorDelay != nil {
		in, out := &in.LibraryMonitorDelay, &out.LibraryMonitorDelay
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinServer.
func (in *JellyfinServer) DeepCopy() *JellyfinServer {
	if in == nil {
		return nil
	}
	out := new(JellyfinServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexConfig) DeepCopyInto(out *PlexConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexConfig.
func (in *PlexConfig) DeepCopy() *PlexConfig {
	if in == nil {
		return nil
	}
	out := new(PlexConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlexConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexConfigList) DeepCopyInto(out *PlexConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlexConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexConfigList.
func (in *PlexConfigList) DeepCopy() *PlexConfigList {
	if in == nil {
		return nil
	}
	out := new(PlexConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlexConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexConfigSpec) DeepCopyInto(out *PlexConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(PlexServer)
		(*in).DeepCopyInto(*out)
	}
	if in.Transcoder != nil {
		in, out := &in.Transcoder, &out.Transcoder
		*out = new(PlexTranscoder)
		(*in).DeepCopyInto(*out)
	}
	if in.Libraries != nil {
		in, out := &in.Libraries, &out.Libraries
		*out = make([]PlexLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(PlexNetwork)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexConfigSpec.
func (in *PlexConfigSpec) DeepCopy() *PlexConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PlexConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexConfigStatus) DeepCopyInto(out *PlexConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexConfigStatus.
func (in *PlexConfigStatus) DeepCopy() *PlexConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PlexConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexConnection) DeepCopyInto(out *PlexConnection) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(commonv1alpha1.TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexConnection.
func (in *PlexConnection) DeepCopy() *PlexConnection {
	if in == nil {
		return nil
	}
	out := new(PlexConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexLibrary) DeepCopyInto(out *PlexLibrary) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexLibrary.
func (in *PlexLibrary) DeepCopy() *PlexLibrary {
	if in == nil {
		return nil
	}
	out := new(PlexLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexNetwork) DeepCopyInto(out *PlexNetwork) {
	*out = *in
	if in.SecureConnections != nil {
		in, out := &in.SecureConnections, &out.SecureConnections
		*out = new(int)
		**out = **in
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexNetwork.
func (in *PlexNetwork) DeepCopy() *PlexNetwork {
	if in == nil {
		return nil
	}
	out := new(PlexNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexServer) DeepCopyInto(out *PlexServer) {
	*out = *in
	if in.EnableRemoteAccess != nil {
		in, out := &in.EnableRemoteAccess, &out.EnableRemoteAccess
		*out = new(bool)
		**out = **in
	}
	if in.LogDebug != nil {
		in, out := &in.LogDebug, &out.LogDebug
		*out = new(bool)
		**out = **in
	}
	if in.AutoEmptyTrash != nil {
		in, out := &in.AutoEmptyTrash, &out.AutoEmptyTrash
		*out = new(bool)
		**out = **in
	}
	if in.ScanMyLibraryAutomatically != nil {
		in, out := &in.ScanMyLibraryAutomatically, &out.ScanMyLibraryAutomatically
		*out = new(bool)
		**out = **in
	}
	if in.ScanMyLibraryPeriodically != nil {
		in, out := &in.ScanMyLibraryPeriodically, &out.ScanMyLibraryPeriodically
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexServer.
func (in *PlexServer) DeepCopy() *PlexServer {
	if in == nil {
		return nil
	}
	out := new(PlexServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexTranscoder) DeepCopyInto(out *PlexTranscoder) {
	*out = *in
	if in.TranscodeHwRequested != nil {
		in, out := &in.TranscodeHwRequested, &out.TranscodeHwRequested
		*out = new(bool)
		**out = **in
	}
	if in.MaxSimultaneousVideoTranscodes != nil {
		in, out := &in.MaxSimultaneousVideoTranscodes, &out.MaxSimultaneousVideoTranscodes
		*out = new(int)
		**out = **in
	}
	if in.TranscodeHwDecodingEnabled != nil {
		in, out := &in.TranscodeHwDecodingEnabled, &out.TranscodeHwDecodingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TranscodeHwEncodingEnabled != nil {
		in, out := &in.TranscodeHwEncodingEnabled, &out.TranscodeHwEncodingEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexTranscoder.
func (in *PlexTranscoder) DeepCopy() *PlexTranscoder {
	if in == nil {
		return nil
	}
	out := new(PlexTranscoder)
	in.DeepCopyInto(out)
	return out
}
