{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "media-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "media-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "media-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: https
      scheme: https
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
