//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kyleseneker/media-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrAppConnection) DeepCopyInto(out *BazarrAppConnection) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	out.APIKeySecretRef = in.APIKeySecretRef
	if in.HttpTimeout != nil {
		in, out := &in.HttpTimeout, &out.HttpTimeout
		*out = new(int)
		**out = **in
	}
	if in.OnlyMonitored != nil {
		in, out := &in.OnlyMonitored, &out.OnlyMonitored
		*out = new(bool)
		**out = **in
	}
	if in.SyncInterval != nil {
		in, out := &in.SyncInterval, &out.SyncInterval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrAppConnection.
func (in *BazarrAppConnection) DeepCopy() *BazarrAppConnection {
	if in == nil {
		return nil
	}
	out := new(BazarrAppConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfig) DeepCopyInto(out *BazarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfig.
func (in *BazarrConfig) DeepCopy() *BazarrConfig {
	if in == nil {
		return nil
	}
	out := new(BazarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BazarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigList) DeepCopyInto(out *BazarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BazarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigList.
func (in *BazarrConfigList) DeepCopy() *BazarrConfigList {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BazarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigSpec) DeepCopyInto(out *BazarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.General != nil {
		in, out := &in.General, &out.General
		*out = new(BazarrGeneral)
		(*in).DeepCopyInto(*out)
	}
	if in.SonarrConnection != nil {
		in, out := &in.SonarrConnection, &out.SonarrConnection
		*out = new(BazarrAppConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.RadarrConnection != nil {
		in, out := &in.RadarrConnection, &out.RadarrConnection
		*out = new(BazarrAppConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.SubSync != nil {
		in, out := &in.SubSync, &out.SubSync
		*out = new(BazarrSubSync)
		(*in).DeepCopyInto(*out)
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]BazarrProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Languages != nil {
		in, out := &in.Languages, &out.Languages
		*out = new(BazarrLanguages)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigSpec.
func (in *BazarrConfigSpec) DeepCopy() *BazarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigStatus) DeepCopyInto(out *BazarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigStatus.
func (in *BazarrConfigStatus) DeepCopy() *BazarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrGeneral) DeepCopyInto(out *BazarrGeneral) {
	*out = *in
	if in.UseSonarr != nil {
		in, out := &in.UseSonarr, &out.UseSonarr
		*out = new(bool)
		**out = **in
	}
	if in.UseRadarr != nil {
		in, out := &in.UseRadarr, &out.UseRadarr
		*out = new(bool)
		**out = **in
	}
	if in.MinimumScore != nil {
		in, out := &in.MinimumScore, &out.MinimumScore
		*out = new(int)
		**out = **in
	}
	if in.MinimumScoreMovie != nil {
		in, out := &in.MinimumScoreMovie, &out.MinimumScoreMovie
		*out = new(int)
		**out = **in
	}
	if in.UseScenename != nil {
		in, out := &in.UseScenename, &out.UseScenename
		*out = new(bool)
		**out = **in
	}
	if in.UsePostprocessing != nil {
		in, out := &in.UsePostprocessing, &out.UsePostprocessing
		*out = new(bool)
		**out = **in
	}
	if in.AdaptiveSearching != nil {
		in, out := &in.AdaptiveSearching, &out.AdaptiveSearching
		*out = new(bool)
		**out = **in
	}
	if in.Multithreading != nil {
		in, out := &in.Multithreading, &out.Multithreading
		*out = new(bool)
		**out = **in
	}
	if in.ChmodEnabled != nil {
		in, out := &in.ChmodEnabled, &out.ChmodEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UpgradeSubs != nil {
		in, out := &in.UpgradeSubs, &out.UpgradeSubs
		*out = new(bool)
		**out = **in
	}
	if in.UpgradeFrequency != nil {
		in, out := &in.UpgradeFrequency, &out.UpgradeFrequency
		*out = new(int)
		**out = **in
	}
	if in.WantedSearchFrequency != nil {
		in, out := &in.WantedSearchFrequency, &out.WantedSearchFrequency
		*out = new(int)
		**out = **in
	}
	if in.Utf8Encode != nil {
		in, out := &in.Utf8Encode, &out.Utf8Encode
		*out = new(bool)
		**out = **in
	}
	if in.IgnorePgsSubs != nil {
		in, out := &in.IgnorePgsSubs, &out.IgnorePgsSubs
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreVobsubSubs != nil {
		in, out := &in.IgnoreVobsubSubs, &out.IgnoreVobsubSubs
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreAssSubs != nil {
		in, out := &in.IgnoreAssSubs, &out.IgnoreAssSubs
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrGeneral.
func (in *BazarrGeneral) DeepCopy() *BazarrGeneral {
	if in == nil {
		return nil
	}
	out := new(BazarrGeneral)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrLanguageItem) DeepCopyInto(out *BazarrLanguageItem) {
	*out = *in
	if in.HI != nil {
		in, out := &in.HI, &out.HI
		*out = new(bool)
		**out = **in
	}
	if in.Forced != nil {
		in, out := &in.Forced, &out.Forced
		*out = new(bool)
		**out = **in
	}
	if in.AudioExclude != nil {
		in, out := &in.AudioExclude, &out.AudioExclude
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrLanguageItem.
func (in *BazarrLanguageItem) DeepCopy() *BazarrLanguageItem {
	if in == nil {
		return nil
	}
	out := new(BazarrLanguageItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrLanguageProfile) DeepCopyInto(out *BazarrLanguageProfile) {
	*out = *in
	if in.ProfileId != nil {
		in, out := &in.ProfileId, &out.ProfileId
		*out = new(int)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BazarrLanguageItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrLanguageProfile.
func (in *BazarrLanguageProfile) DeepCopy() *BazarrLanguageProfile {
	if in == nil {
		return nil
	}
	out := new(BazarrLanguageProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrLanguages) DeepCopyInto(out *BazarrLanguages) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]BazarrLanguageProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrLanguages.
func (in *BazarrLanguages) DeepCopy() *BazarrLanguages {
	if in == nil {
		return nil
	}
	out := new(BazarrLanguages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrProvider) DeepCopyInto(out *BazarrProvider) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrProvider.
func (in *BazarrProvider) DeepCopy() *BazarrProvider {
	if in == nil {
		return nil
	}
	out := new(BazarrProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrSubSync) DeepCopyInto(out *BazarrSubSync) {
	*out = *in
	if in.UseSubsync != nil {
		in, out := &in.UseSubsync, &out.UseSubsync
		*out = new(bool)
		**out = **in
	}
	if in.UseSubsyncThreshold != nil {
		in, out := &in.UseSubsyncThreshold, &out.UseSubsyncThreshold
		*out = new(bool)
		**out = **in
	}
	if in.SubsyncThreshold != nil {
		in, out := &in.SubsyncThreshold, &out.SubsyncThreshold
		*out = new(int)
		**out = **in
	}
	if in.UseSubsyncMovieThreshold != nil {
		in, out := &in.UseSubsyncMovieThreshold, &out.UseSubsyncMovieThreshold
		*out = new(bool)
		**out = **in
	}
	if in.SubsyncMovieThreshold != nil {
		in, out := &in.SubsyncMovieThreshold, &out.SubsyncMovieThreshold
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrSubSync.
func (in *BazarrSubSync) DeepCopy() *BazarrSubSync {
	if in == nil {
		return nil
	}
	out := new(BazarrSubSync)
	in.DeepCopyInto(out)
	return out
}
