//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kyleseneker/media-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrAppConnection) DeepCopyInto(out *BazarrAppConnection) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	out.APIKeySecretRef = in.APIKeySecretRef
	if in.HttpTimeout != nil {
		in, out := &in.HttpTimeout, &out.HttpTimeout
		*out = new(int)
		**out = **in
	}
	if in.OnlyMonitored != nil {
		in, out := &in.OnlyMonitored, &out.OnlyMonitored
		*out = new(bool)
		**out = **in
	}
	if in.SyncInterval != nil {
		in, out := &in.SyncInterval, &out.SyncInterval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrAppConnection.
func (in *BazarrAppConnection) DeepCopy() *BazarrAppConnection {
	if in == nil {
		return nil
	}
	out := new(BazarrAppConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfig) DeepCopyInto(out *BazarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfig.
func (in *BazarrConfig) DeepCopy() *BazarrConfig {
	if in == nil {
		return nil
	}
	out := new(BazarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BazarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigList) DeepCopyInto(out *BazarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BazarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigList.
func (in *BazarrConfigList) DeepCopy() *BazarrConfigList {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BazarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigSpec) DeepCopyInto(out *BazarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.General != nil {
		in, out := &in.General, &out.General
		*out = new(BazarrGeneral)
		(*in).DeepCopyInto(*out)
	}
	if in.SonarrConnection != nil {
		in, out := &in.SonarrConnection, &out.SonarrConnection
		*out = new(BazarrAppConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.RadarrConnection != nil {
		in, out := &in.RadarrConnection, &out.RadarrConnection
		*out = new(BazarrAppConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.SubSync != nil {
		in, out := &in.SubSync, &out.SubSync
		*out = new(BazarrSubSync)
		(*in).DeepCopyInto(*out)
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]BazarrProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Languages != nil {
		in, out := &in.Languages, &out.Languages
		*out = new(BazarrLanguages)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigSpec.
func (in *BazarrConfigSpec) DeepCopy() *BazarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrConfigStatus) DeepCopyInto(out *BazarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrConfigStatus.
func (in *BazarrConfigStatus) DeepCopy() *BazarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BazarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrGeneral) DeepCopyInto(out *BazarrGeneral) {
	*out = *in
	if in.UseSonarr != nil {
		in, out := &in.UseSonarr, &out.UseSonarr
		*out = new(bool)
		**out = **in
	}
	if in.UseRadarr != nil {
		in, out := &in.UseRadarr, &out.UseRadarr
		*out = new(bool)
		**out = **in
	}
	if in.MinimumScore != nil {
		in, out := &in.MinimumScore, &out.MinimumScore
		*out = new(int)
		**out = **in
	}
	if in.MinimumScoreMovie != nil {
		in, out := &in.MinimumScoreMovie, &out.MinimumScoreMovie
		*out = new(int)
		**out = **in
	}
	if in.UseScenename != nil {
		in, out := &in.UseScenename, &out.UseScenename
		*out = new(bool)
		**out = **in
	}
	if in.UsePostprocessing != nil {
		in, out := &in.UsePostprocessing, &out.UsePostprocessing
		*out = new(bool)
		**out = **in
	}
	if in.AdaptiveSearching != nil {
		in, out := &in.AdaptiveSearching, &out.AdaptiveSearching
		*out = new(bool)
		**out = **in
	}
	if in.Multithreading != nil {
		in, out := &in.Multithreading, &out.Multithreading
		*out = new(bool)
		**out = **in
	}
	if in.ChmodEnabled != nil {
		in, out := &in.ChmodEnabled, &out.ChmodEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UpgradeSubs != nil {
		in, out := &in.UpgradeSubs, &out.UpgradeSubs
		*out = new(bool)
		**out = **in
	}
	if in.UpgradeFrequency != nil {
		in, out := &in.UpgradeFrequency, &out.UpgradeFrequency
		*out = new(int)
		**out = **in
	}
	if in.WantedSearchFrequency != nil {
		in, out := &in.WantedSearchFrequency, &out.WantedSearchFrequency
		*out = new(int)
		**out = **in
	}
	if in.Utf8Encode != nil {
		in, out := &in.Utf8Encode, &out.Utf8Encode
		*out = new(bool)
		**out = **in
	}
	if in.IgnorePgsSubs != nil {
		in, out := &in.IgnorePgsSubs, &out.IgnorePgsSubs
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreVobsubSubs != nil {
		in, out := &in.IgnoreVobsubSubs, &out.IgnoreVobsubSubs
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreAssSubs != nil {
		in, out := &in.IgnoreAssSubs, &out.IgnoreAssSubs
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrGeneral.
func (in *BazarrGeneral) DeepCopy() *BazarrGeneral {
	if in == nil {
		return nil
	}
	out := new(BazarrGeneral)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrLanguageItem) DeepCopyInto(out *BazarrLanguageItem) {
	*out = *in
	if in.HI != nil {
		in, out := &in.HI, &out.HI
		*out = new(bool)
		**out = **in
	}
	if in.Forced != nil {
		in, out := &in.Forced, &out.Forced
		*out = new(bool)
		**out = **in
	}
	if in.AudioExclude != nil {
		in, out := &in.AudioExclude, &out.AudioExclude
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrLanguageItem.
func (in *BazarrLanguageItem) DeepCopy() *BazarrLanguageItem {
	if in == nil {
		return nil
	}
	out := new(BazarrLanguageItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrLanguageProfile) DeepCopyInto(out *BazarrLanguageProfile) {
	*out = *in
	if in.ProfileId != nil {
		in, out := &in.ProfileId, &out.ProfileId
		*out = new(int)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BazarrLanguageItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrLanguageProfile.
func (in *BazarrLanguageProfile) DeepCopy() *BazarrLanguageProfile {
	if in == nil {
		return nil
	}
	out := new(BazarrLanguageProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrLanguages) DeepCopyInto(out *BazarrLanguages) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]BazarrLanguageProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrLanguages.
func (in *BazarrLanguages) DeepCopy() *BazarrLanguages {
	if in == nil {
		return nil
	}
	out := new(BazarrLanguages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrProvider) DeepCopyInto(out *BazarrProvider) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrProvider.
func (in *BazarrProvider) DeepCopy() *BazarrProvider {
	if in == nil {
		return nil
	}
	out := new(BazarrProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BazarrSubSync) DeepCopyInto(out *BazarrSubSync) {
	*out = *in
	if in.UseSubsync != nil {
		in, out := &in.UseSubsync, &out.UseSubsync
		*out = new(bool)
		**out = **in
	}
	if in.UseSubsyncThreshold != nil {
		in, out := &in.UseSubsyncThreshold, &out.UseSubsyncThreshold
		*out = new(bool)
		**out = **in
	}
	if in.SubsyncThreshold != nil {
		in, out := &in.SubsyncThreshold, &out.SubsyncThreshold
		*out = new(int)
		**out = **in
	}
	if in.UseSubsyncMovieThreshold != nil {
		in, out := &in.UseSubsyncMovieThreshold, &out.UseSubsyncMovieThreshold
		*out = new(bool)
		**out = **in
	}
	if in.SubsyncMovieThreshold != nil {
		in, out := &in.SubsyncMovieThreshold, &out.SubsyncMovieThreshold
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BazarrSubSync.
func (in *BazarrSubSync) DeepCopy() *BazarrSubSync {
	if in == nil {
		return nil
	}
	out := new(BazarrSubSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfig) DeepCopyInto(out *LidarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfig.
func (in *LidarrConfig) DeepCopy() *LidarrConfig {
	if in == nil {
		return nil
	}
	out := new(LidarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LidarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigList) DeepCopyInto(out *LidarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LidarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigList.
func (in *LidarrConfigList) DeepCopy() *LidarrConfigList {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LidarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigSpec) DeepCopyInto(out *LidarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MediaManagement != nil {
		in, out := &in.MediaManagement, &out.MediaManagement
		*out = new(LidarrMediaManagement)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(LidarrNaming)
		(*in).DeepCopyInto(*out)
	}
	if in.IndexerConfig != nil {
		in, out := &in.IndexerConfig, &out.IndexerConfig
		*out = new(LidarrIndexerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClientConfig != nil {
		in, out := &in.DownloadClientConfig, &out.DownloadClientConfig
		*out = new(LidarrDownloadClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(LidarrUI)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]commonv1alpha1.RootFolder, len(*in))
		copy(*out, *in)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]commonv1alpha1.DownloadClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QualityProfiles != nil {
		in, out := &in.QualityProfiles, &out.QualityProfiles
		*out = make([]commonv1alpha1.QualityProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomFormats != nil {
		in, out := &in.CustomFormats, &out.CustomFormats
		*out = make([]commonv1alpha1.CustomFormat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]commonv1alpha1.Tag, len(*in))
		copy(*out, *in)
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]commonv1alpha1.Indexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]commonv1alpha1.Notification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImportLists != nil {
		in, out := &in.ImportLists, &out.ImportLists
		*out = make([]commonv1alpha1.ImportList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigSpec.
func (in *LidarrConfigSpec) DeepCopy() *LidarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrConfigStatus) DeepCopyInto(out *LidarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrConfigStatus.
func (in *LidarrConfigStatus) DeepCopy() *LidarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LidarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrDownloadClientConfig) DeepCopyInto(out *LidarrDownloadClientConfig) {
	*out = *in
	if in.EnableCompletedDownloadHandling != nil {
		in, out := &in.EnableCompletedDownloadHandling, &out.EnableCompletedDownloadHandling
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedownloadFailed != nil {
		in, out := &in.AutoRedownloadFailed, &out.AutoRedownloadFailed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrDownloadClientConfig.
func (in *LidarrDownloadClientConfig) DeepCopy() *LidarrDownloadClientConfig {
	if in == nil {
		return nil
	}
	out := new(LidarrDownloadClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrIndexerConfig) DeepCopyInto(out *LidarrIndexerConfig) {
	*out = *in
	if in.MinimumAge != nil {
		in, out := &in.MinimumAge, &out.MinimumAge
		*out = new(int)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(int)
		**out = **in
	}
	if in.MaximumSize != nil {
		in, out := &in.MaximumSize, &out.MaximumSize
		*out = new(int)
		**out = **in
	}
	if in.RssSyncInterval != nil {
		in, out := &in.RssSyncInterval, &out.RssSyncInterval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrIndexerConfig.
func (in *LidarrIndexerConfig) DeepCopy() *LidarrIndexerConfig {
	if in == nil {
		return nil
	}
	out := new(LidarrIndexerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrMediaManagement) DeepCopyInto(out *LidarrMediaManagement) {
	*out = *in
	if in.CopyUsingHardlinks != nil {
		in, out := &in.CopyUsingHardlinks, &out.CopyUsingHardlinks
		*out = new(bool)
		**out = **in
	}
	if in.DeleteEmptyFolders != nil {
		in, out := &in.DeleteEmptyFolders, &out.DeleteEmptyFolders
		*out = new(bool)
		**out = **in
	}
	if in.ImportExtraFiles != nil {
		in, out := &in.ImportExtraFiles, &out.ImportExtraFiles
		*out = new(bool)
		**out = **in
	}
	if in.RecycleBinCleanupDays != nil {
		in, out := &in.RecycleBinCleanupDays, &out.RecycleBinCleanupDays
		*out = new(int)
		**out = **in
	}
	if in.MinimumFreeSpaceWhenImporting != nil {
		in, out := &in.MinimumFreeSpaceWhenImporting, &out.MinimumFreeSpaceWhenImporting
		*out = new(int)
		**out = **in
	}
	if in.SetPermissionsLinux != nil {
		in, out := &in.SetPermissionsLinux, &out.SetPermissionsLinux
		*out = new(bool)
		**out = **in
	}
	if in.CreateEmptyArtistFolders != nil {
		in, out := &in.CreateEmptyArtistFolders, &out.CreateEmptyArtistFolders
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrMediaManagement.
func (in *LidarrMediaManagement) DeepCopy() *LidarrMediaManagement {
	if in == nil {
		return nil
	}
	out := new(LidarrMediaManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrNaming) DeepCopyInto(out *LidarrNaming) {
	*out = *in
	if in.RenameTracks != nil {
		in, out := &in.RenameTracks, &out.RenameTracks
		*out = new(bool)
		**out = **in
	}
	if in.ReplaceIllegalCharacters != nil {
		in, out := &in.ReplaceIllegalCharacters, &out.ReplaceIllegalCharacters
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrNaming.
func (in *LidarrNaming) DeepCopy() *LidarrNaming {
	if in == nil {
		return nil
	}
	out := new(LidarrNaming)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LidarrUI) DeepCopyInto(out *LidarrUI) {
	*out = *in
	if in.FirstDayOfWeek != nil {
		in, out := &in.FirstDayOfWeek, &out.FirstDayOfWeek
		*out = new(int)
		**out = **in
	}
	if in.UILanguage != nil {
		in, out := &in.UILanguage, &out.UILanguage
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LidarrUI.
func (in *LidarrUI) DeepCopy() *LidarrUI {
	if in == nil {
		return nil
	}
	out := new(LidarrUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrApplication) DeepCopyInto(out *ProwlarrApplication) {
	*out = *in
	out.APIKeySecretRef = in.APIKeySecretRef
	if in.SyncCategories != nil {
		in, out := &in.SyncCategories, &out.SyncCategories
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrApplication.
func (in *ProwlarrApplication) DeepCopy() *ProwlarrApplication {
	if in == nil {
		return nil
	}
	out := new(ProwlarrApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfig) DeepCopyInto(out *ProwlarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfig.
func (in *ProwlarrConfig) DeepCopy() *ProwlarrConfig {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProwlarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigList) DeepCopyInto(out *ProwlarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProwlarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigList.
func (in *ProwlarrConfigList) DeepCopy() *ProwlarrConfigList {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProwlarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigSpec) DeepCopyInto(out *ProwlarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Applications != nil {
		in, out := &in.Applications, &out.Applications
		*out = make([]ProwlarrApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]ProwlarrIndexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Proxies != nil {
		in, out := &in.Proxies, &out.Proxies
		*out = make([]ProwlarrProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]commonv1alpha1.Tag, len(*in))
		copy(*out, *in)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]ProwlarrDownloadClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]commonv1alpha1.Notification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigSpec.
func (in *ProwlarrConfigSpec) DeepCopy() *ProwlarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrConfigStatus) DeepCopyInto(out *ProwlarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrConfigStatus.
func (in *ProwlarrConfigStatus) DeepCopy() *ProwlarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ProwlarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrDownloadClient) DeepCopyInto(out *ProwlarrDownloadClient) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]ProwlarrDownloadClientCategory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]ProwlarrField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrDownloadClient.
func (in *ProwlarrDownloadClient) DeepCopy() *ProwlarrDownloadClient {
	if in == nil {
		return nil
	}
	out := new(ProwlarrDownloadClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrDownloadClientCategory) DeepCopyInto(out *ProwlarrDownloadClientCategory) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrDownloadClientCategory.
func (in *ProwlarrDownloadClientCategory) DeepCopy() *ProwlarrDownloadClientCategory {
	if in == nil {
		return nil
	}
	out := new(ProwlarrDownloadClientCategory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrField) DeepCopyInto(out *ProwlarrField) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrField.
func (in *ProwlarrField) DeepCopy() *ProwlarrField {
	if in == nil {
		return nil
	}
	out := new(ProwlarrField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrIndexer) DeepCopyInto(out *ProwlarrIndexer) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.AppProfileId != nil {
		in, out := &in.AppProfileId, &out.AppProfileId
		*out = new(int)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]ProwlarrField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrIndexer.
func (in *ProwlarrIndexer) DeepCopy() *ProwlarrIndexer {
	if in == nil {
		return nil
	}
	out := new(ProwlarrIndexer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProwlarrProxy) DeepCopyInto(out *ProwlarrProxy) {
	*out = *in
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(int)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProwlarrProxy.
func (in *ProwlarrProxy) DeepCopy() *ProwlarrProxy {
	if in == nil {
		return nil
	}
	out := new(ProwlarrProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfig) DeepCopyInto(out *RadarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfig.
func (in *RadarrConfig) DeepCopy() *RadarrConfig {
	if in == nil {
		return nil
	}
	out := new(RadarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigList) DeepCopyInto(out *RadarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RadarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigList.
func (in *RadarrConfigList) DeepCopy() *RadarrConfigList {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigSpec) DeepCopyInto(out *RadarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MediaManagement != nil {
		in, out := &in.MediaManagement, &out.MediaManagement
		*out = new(RadarrMediaManagement)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(RadarrNaming)
		(*in).DeepCopyInto(*out)
	}
	if in.IndexerConfig != nil {
		in, out := &in.IndexerConfig, &out.IndexerConfig
		*out = new(RadarrIndexerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClientConfig != nil {
		in, out := &in.DownloadClientConfig, &out.DownloadClientConfig
		*out = new(RadarrDownloadClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(RadarrUI)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]commonv1alpha1.RootFolder, len(*in))
		copy(*out, *in)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]commonv1alpha1.DownloadClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QualityProfiles != nil {
		in, out := &in.QualityProfiles, &out.QualityProfiles
		*out = make([]commonv1alpha1.QualityProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomFormats != nil {
		in, out := &in.CustomFormats, &out.CustomFormats
		*out = make([]commonv1alpha1.CustomFormat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]commonv1alpha1.Tag, len(*in))
		copy(*out, *in)
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]commonv1alpha1.Indexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]commonv1alpha1.Notification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImportLists != nil {
		in, out := &in.ImportLists, &out.ImportLists
		*out = make([]commonv1alpha1.ImportList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigSpec.
func (in *RadarrConfigSpec) DeepCopy() *RadarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrConfigStatus) DeepCopyInto(out *RadarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrConfigStatus.
func (in *RadarrConfigStatus) DeepCopy() *RadarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RadarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrDownloadClientConfig) DeepCopyInto(out *RadarrDownloadClientConfig) {
	*out = *in
	if in.EnableCompletedDownloadHandling != nil {
		in, out := &in.EnableCompletedDownloadHandling, &out.EnableCompletedDownloadHandling
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedownloadFailed != nil {
		in, out := &in.AutoRedownloadFailed, &out.AutoRedownloadFailed
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedownloadFailedFromInteractiveSearch != nil {
		in, out := &in.AutoRedownloadFailedFromInteractiveSearch, &out.AutoRedownloadFailedFromInteractiveSearch
		*out = new(bool)
		**out = **in
	}
	if in.CheckForFinishedDownloadInterval != nil {
		in, out := &in.CheckForFinishedDownloadInterval, &out.CheckForFinishedDownloadInterval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrDownloadClientConfig.
func (in *RadarrDownloadClientConfig) DeepCopy() *RadarrDownloadClientConfig {
	if in == nil {
		return nil
	}
	out := new(RadarrDownloadClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrIndexerConfig) DeepCopyInto(out *RadarrIndexerConfig) {
	*out = *in
	if in.MinimumAge != nil {
		in, out := &in.MinimumAge, &out.MinimumAge
		*out = new(int)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(int)
		**out = **in
	}
	if in.MaximumSize != nil {
		in, out := &in.MaximumSize, &out.MaximumSize
		*out = new(int)
		**out = **in
	}
	if in.RssSyncInterval != nil {
		in, out := &in.RssSyncInterval, &out.RssSyncInterval
		*out = new(int)
		**out = **in
	}
	if in.PreferIndexerFlags != nil {
		in, out := &in.PreferIndexerFlags, &out.PreferIndexerFlags
		*out = new(bool)
		**out = **in
	}
	if in.AvailabilityDelay != nil {
		in, out := &in.AvailabilityDelay, &out.AvailabilityDelay
		*out = new(int)
		**out = **in
	}
	if in.AllowHardcodedSubs != nil {
		in, out := &in.AllowHardcodedSubs, &out.AllowHardcodedSubs
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrIndexerConfig.
func (in *RadarrIndexerConfig) DeepCopy() *RadarrIndexerConfig {
	if in == nil {
		return nil
	}
	out := new(RadarrIndexerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrMediaManagement) DeepCopyInto(out *RadarrMediaManagement) {
	*out = *in
	if in.AutoUnmonitorPreviouslyDownloadedMovies != nil {
		in, out := &in.AutoUnmonitorPreviouslyDownloadedMovies, &out.AutoUnmonitorPreviouslyDownloadedMovies
		*out = new(bool)
		**out = **in
	}
	if in.CreateEmptyMovieFolders != nil {
		in, out := &in.CreateEmptyMovieFolders, &out.CreateEmptyMovieFolders
		*out = new(bool)
		**out = **in
	}
	if in.AutoRenameFolders != nil {
		in, out := &in.AutoRenameFolders, &out.AutoRenameFolders
		*out = new(bool)
		**out = **in
	}
	if in.PathsDefaultStatic != nil {
		in, out := &in.PathsDefaultStatic, &out.PathsDefaultStatic
		*out = new(bool)
		**out = **in
	}
	if in.CopyUsingHardlinks != nil {
		in, out := &in.CopyUsingHardlinks, &out.CopyUsingHardlinks
		*out = new(bool)
		**out = **in
	}
	if in.DeleteEmptyFolders != nil {
		in, out := &in.DeleteEmptyFolders, &out.DeleteEmptyFolders
		*out = new(bool)
		**out = **in
	}
	if in.ImportExtraFiles != nil {
		in, out := &in.ImportExtraFiles, &out.ImportExtraFiles
		*out = new(bool)
		**out = **in
	}
	if in.RecycleBinCleanupDays != nil {
		in, out := &in.RecycleBinCleanupDays, &out.RecycleBinCleanupDays
		*out = new(int)
		**out = **in
	}
	if in.MinimumFreeSpaceWhenImporting != nil {
		in, out := &in.MinimumFreeSpaceWhenImporting, &out.MinimumFreeSpaceWhenImporting
		*out = new(int)
		**out = **in
	}
	if in.EnableMediaInfo != nil {
		in, out := &in.EnableMediaInfo, &out.EnableMediaInfo
		*out = new(bool)
		**out = **in
	}
	if in.SetPermissionsLinux != nil {
		in, out := &in.SetPermissionsLinux, &out.SetPermissionsLinux
		*out = new(bool)
		**out = **in
	}
	if in.SkipFreeSpaceCheckWhenImporting != nil {
		in, out := &in.SkipFreeSpaceCheckWhenImporting, &out.SkipFreeSpaceCheckWhenImporting
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrMediaManagement.
func (in *RadarrMediaManagement) DeepCopy() *RadarrMediaManagement {
	if in == nil {
		return nil
	}
	out := new(RadarrMediaManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrNaming) DeepCopyInto(out *RadarrNaming) {
	*out = *in
	if in.RenameMovies != nil {
		in, out := &in.RenameMovies, &out.RenameMovies
		*out = new(bool)
		**out = **in
	}
	if in.ReplaceIllegalCharacters != nil {
		in, out := &in.ReplaceIllegalCharacters, &out.ReplaceIllegalCharacters
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrNaming.
func (in *RadarrNaming) DeepCopy() *RadarrNaming {
	if in == nil {
		return nil
	}
	out := new(RadarrNaming)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadarrUI) DeepCopyInto(out *RadarrUI) {
	*out = *in
	if in.FirstDayOfWeek != nil {
		in, out := &in.FirstDayOfWeek, &out.FirstDayOfWeek
		*out = new(int)
		**out = **in
	}
	if in.ShowRelativeDates != nil {
		in, out := &in.ShowRelativeDates, &out.ShowRelativeDates
		*out = new(bool)
		**out = **in
	}
	if in.EnableColorImpairedMode != nil {
		in, out := &in.EnableColorImpairedMode, &out.EnableColorImpairedMode
		*out = new(bool)
		**out = **in
	}
	if in.UILanguage != nil {
		in, out := &in.UILanguage, &out.UILanguage
		*out = new(int)
		**out = **in
	}
	if in.MovieInfoLanguage != nil {
		in, out := &in.MovieInfoLanguage, &out.MovieInfoLanguage
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadarrUI.
func (in *RadarrUI) DeepCopy() *RadarrUI {
	if in == nil {
		return nil
	}
	out := new(RadarrUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrConfig) DeepCopyInto(out *ReadarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrConfig.
func (in *ReadarrConfig) DeepCopy() *ReadarrConfig {
	if in == nil {
		return nil
	}
	out := new(ReadarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReadarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrConfigList) DeepCopyInto(out *ReadarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReadarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrConfigList.
func (in *ReadarrConfigList) DeepCopy() *ReadarrConfigList {
	if in == nil {
		return nil
	}
	out := new(ReadarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReadarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrConfigSpec) DeepCopyInto(out *ReadarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MediaManagement != nil {
		in, out := &in.MediaManagement, &out.MediaManagement
		*out = new(ReadarrMediaManagement)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(ReadarrNaming)
		(*in).DeepCopyInto(*out)
	}
	if in.IndexerConfig != nil {
		in, out := &in.IndexerConfig, &out.IndexerConfig
		*out = new(ReadarrIndexerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClientConfig != nil {
		in, out := &in.DownloadClientConfig, &out.DownloadClientConfig
		*out = new(ReadarrDownloadClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(ReadarrUI)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]commonv1alpha1.RootFolder, len(*in))
		copy(*out, *in)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]commonv1alpha1.DownloadClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QualityProfiles != nil {
		in, out := &in.QualityProfiles, &out.QualityProfiles
		*out = make([]commonv1alpha1.QualityProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomFormats != nil {
		in, out := &in.CustomFormats, &out.CustomFormats
		*out = make([]commonv1alpha1.CustomFormat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]commonv1alpha1.Tag, len(*in))
		copy(*out, *in)
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]commonv1alpha1.Indexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]commonv1alpha1.Notification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImportLists != nil {
		in, out := &in.ImportLists, &out.ImportLists
		*out = make([]commonv1alpha1.ImportList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrConfigSpec.
func (in *ReadarrConfigSpec) DeepCopy() *ReadarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ReadarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrConfigStatus) DeepCopyInto(out *ReadarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrConfigStatus.
func (in *ReadarrConfigStatus) DeepCopy() *ReadarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ReadarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrDownloadClientConfig) DeepCopyInto(out *ReadarrDownloadClientConfig) {
	*out = *in
	if in.EnableCompletedDownloadHandling != nil {
		in, out := &in.EnableCompletedDownloadHandling, &out.EnableCompletedDownloadHandling
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedownloadFailed != nil {
		in, out := &in.AutoRedownloadFailed, &out.AutoRedownloadFailed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrDownloadClientConfig.
func (in *ReadarrDownloadClientConfig) DeepCopy() *ReadarrDownloadClientConfig {
	if in == nil {
		return nil
	}
	out := new(ReadarrDownloadClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrIndexerConfig) DeepCopyInto(out *ReadarrIndexerConfig) {
	*out = *in
	if in.MinimumAge != nil {
		in, out := &in.MinimumAge, &out.MinimumAge
		*out = new(int)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(int)
		**out = **in
	}
	if in.MaximumSize != nil {
		in, out := &in.MaximumSize, &out.MaximumSize
		*out = new(int)
		**out = **in
	}
	if in.RssSyncInterval != nil {
		in, out := &in.RssSyncInterval, &out.RssSyncInterval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrIndexerConfig.
func (in *ReadarrIndexerConfig) DeepCopy() *ReadarrIndexerConfig {
	if in == nil {
		return nil
	}
	out := new(ReadarrIndexerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrMediaManagement) DeepCopyInto(out *ReadarrMediaManagement) {
	*out = *in
	if in.CopyUsingHardlinks != nil {
		in, out := &in.CopyUsingHardlinks, &out.CopyUsingHardlinks
		*out = new(bool)
		**out = **in
	}
	if in.DeleteEmptyFolders != nil {
		in, out := &in.DeleteEmptyFolders, &out.DeleteEmptyFolders
		*out = new(bool)
		**out = **in
	}
	if in.ImportExtraFiles != nil {
		in, out := &in.ImportExtraFiles, &out.ImportExtraFiles
		*out = new(bool)
		**out = **in
	}
	if in.RecycleBinCleanupDays != nil {
		in, out := &in.RecycleBinCleanupDays, &out.RecycleBinCleanupDays
		*out = new(int)
		**out = **in
	}
	if in.MinimumFreeSpaceWhenImporting != nil {
		in, out := &in.MinimumFreeSpaceWhenImporting, &out.MinimumFreeSpaceWhenImporting
		*out = new(int)
		**out = **in
	}
	if in.SetPermissionsLinux != nil {
		in, out := &in.SetPermissionsLinux, &out.SetPermissionsLinux
		*out = new(bool)
		**out = **in
	}
	if in.CreateEmptyAuthorFolders != nil {
		in, out := &in.CreateEmptyAuthorFolders, &out.CreateEmptyAuthorFolders
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrMediaManagement.
func (in *ReadarrMediaManagement) DeepCopy() *ReadarrMediaManagement {
	if in == nil {
		return nil
	}
	out := new(ReadarrMediaManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrNaming) DeepCopyInto(out *ReadarrNaming) {
	*out = *in
	if in.RenameBooks != nil {
		in, out := &in.RenameBooks, &out.RenameBooks
		*out = new(bool)
		**out = **in
	}
	if in.ReplaceIllegalCharacters != nil {
		in, out := &in.ReplaceIllegalCharacters, &out.ReplaceIllegalCharacters
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrNaming.
func (in *ReadarrNaming) DeepCopy() *ReadarrNaming {
	if in == nil {
		return nil
	}
	out := new(ReadarrNaming)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadarrUI) DeepCopyInto(out *ReadarrUI) {
	*out = *in
	if in.FirstDayOfWeek != nil {
		in, out := &in.FirstDayOfWeek, &out.FirstDayOfWeek
		*out = new(int)
		**out = **in
	}
	if in.UILanguage != nil {
		in, out := &in.UILanguage, &out.UILanguage
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadarrUI.
func (in *ReadarrUI) DeepCopy() *ReadarrUI {
	if in == nil {
		return nil
	}
	out := new(ReadarrUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfig) DeepCopyInto(out *SonarrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfig.
func (in *SonarrConfig) DeepCopy() *SonarrConfig {
	if in == nil {
		return nil
	}
	out := new(SonarrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonarrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigList) DeepCopyInto(out *SonarrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SonarrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigList.
func (in *SonarrConfigList) DeepCopy() *SonarrConfigList {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonarrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigSpec) DeepCopyInto(out *SonarrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MediaManagement != nil {
		in, out := &in.MediaManagement, &out.MediaManagement
		*out = new(SonarrMediaManagement)
		(*in).DeepCopyInto(*out)
	}
	if in.Naming != nil {
		in, out := &in.Naming, &out.Naming
		*out = new(SonarrNaming)
		(*in).DeepCopyInto(*out)
	}
	if in.IndexerConfig != nil {
		in, out := &in.IndexerConfig, &out.IndexerConfig
		*out = new(SonarrIndexerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DownloadClientConfig != nil {
		in, out := &in.DownloadClientConfig, &out.DownloadClientConfig
		*out = new(SonarrDownloadClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(SonarrUI)
		(*in).DeepCopyInto(*out)
	}
	if in.RootFolders != nil {
		in, out := &in.RootFolders, &out.RootFolders
		*out = make([]commonv1alpha1.RootFolder, len(*in))
		copy(*out, *in)
	}
	if in.DownloadClients != nil {
		in, out := &in.DownloadClients, &out.DownloadClients
		*out = make([]commonv1alpha1.DownloadClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QualityProfiles != nil {
		in, out := &in.QualityProfiles, &out.QualityProfiles
		*out = make([]commonv1alpha1.QualityProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomFormats != nil {
		in, out := &in.CustomFormats, &out.CustomFormats
		*out = make([]commonv1alpha1.CustomFormat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]commonv1alpha1.Tag, len(*in))
		copy(*out, *in)
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]commonv1alpha1.Indexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]commonv1alpha1.Notification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImportLists != nil {
		in, out := &in.ImportLists, &out.ImportLists
		*out = make([]commonv1alpha1.ImportList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigSpec.
func (in *SonarrConfigSpec) DeepCopy() *SonarrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrConfigStatus) DeepCopyInto(out *SonarrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrConfigStatus.
func (in *SonarrConfigStatus) DeepCopy() *SonarrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SonarrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrDownloadClientConfig) DeepCopyInto(out *SonarrDownloadClientConfig) {
	*out = *in
	if in.EnableCompletedDownloadHandling != nil {
		in, out := &in.EnableCompletedDownloadHandling, &out.EnableCompletedDownloadHandling
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedownloadFailed != nil {
		in, out := &in.AutoRedownloadFailed, &out.AutoRedownloadFailed
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedownloadFailedFromInteractiveSearch != nil {
		in, out := &in.AutoRedownloadFailedFromInteractiveSearch, &out.AutoRedownloadFailedFromInteractiveSearch
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrDownloadClientConfig.
func (in *SonarrDownloadClientConfig) DeepCopy() *SonarrDownloadClientConfig {
	if in == nil {
		return nil
	}
	out := new(SonarrDownloadClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrIndexerConfig) DeepCopyInto(out *SonarrIndexerConfig) {
	*out = *in
	if in.MinimumAge != nil {
		in, out := &in.MinimumAge, &out.MinimumAge
		*out = new(int)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(int)
		**out = **in
	}
	if in.MaximumSize != nil {
		in, out := &in.MaximumSize, &out.MaximumSize
		*out = new(int)
		**out = **in
	}
	if in.RssSyncInterval != nil {
		in, out := &in.RssSyncInterval, &out.RssSyncInterval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrIndexerConfig.
func (in *SonarrIndexerConfig) DeepCopy() *SonarrIndexerConfig {
	if in == nil {
		return nil
	}
	out := new(SonarrIndexerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrMediaManagement) DeepCopyInto(out *SonarrMediaManagement) {
	*out = *in
	if in.CopyUsingHardlinks != nil {
		in, out := &in.CopyUsingHardlinks, &out.CopyUsingHardlinks
		*out = new(bool)
		**out = **in
	}
	if in.DeleteEmptyFolders != nil {
		in, out := &in.DeleteEmptyFolders, &out.DeleteEmptyFolders
		*out = new(bool)
		**out = **in
	}
	if in.ImportExtraFiles != nil {
		in, out := &in.ImportExtraFiles, &out.ImportExtraFiles
		*out = new(bool)
		**out = **in
	}
	if in.RecycleBinCleanupDays != nil {
		in, out := &in.RecycleBinCleanupDays, &out.RecycleBinCleanupDays
		*out = new(int)
		**out = **in
	}
	if in.MinimumFreeSpaceWhenImporting != nil {
		in, out := &in.MinimumFreeSpaceWhenImporting, &out.MinimumFreeSpaceWhenImporting
		*out = new(int)
		**out = **in
	}
	if in.EnableMediaInfo != nil {
		in, out := &in.EnableMediaInfo, &out.EnableMediaInfo
		*out = new(bool)
		**out = **in
	}
	if in.SetPermissionsLinux != nil {
		in, out := &in.SetPermissionsLinux, &out.SetPermissionsLinux
		*out = new(bool)
		**out = **in
	}
	if in.SkipFreeSpaceCheckWhenImporting != nil {
		in, out := &in.SkipFreeSpaceCheckWhenImporting, &out.SkipFreeSpaceCheckWhenImporting
		*out = new(bool)
		**out = **in
	}
	if in.CreateEmptySeriesFolders != nil {
		in, out := &in.CreateEmptySeriesFolders, &out.CreateEmptySeriesFolders
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrMediaManagement.
func (in *SonarrMediaManagement) DeepCopy() *SonarrMediaManagement {
	if in == nil {
		return nil
	}
	out := new(SonarrMediaManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrNaming) DeepCopyInto(out *SonarrNaming) {
	*out = *in
	if in.RenameEpisodes != nil {
		in, out := &in.RenameEpisodes, &out.RenameEpisodes
		*out = new(bool)
		**out = **in
	}
	if in.ReplaceIllegalCharacters != nil {
		in, out := &in.ReplaceIllegalCharacters, &out.ReplaceIllegalCharacters
		*out = new(bool)
		**out = **in
	}
	if in.ColonReplacementFormat != nil {
		in, out := &in.ColonReplacementFormat, &out.ColonReplacementFormat
		*out = new(int)
		**out = **in
	}
	if in.MultiEpisodeStyle != nil {
		in, out := &in.MultiEpisodeStyle, &out.MultiEpisodeStyle
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrNaming.
func (in *SonarrNaming) DeepCopy() *SonarrNaming {
	if in == nil {
		return nil
	}
	out := new(SonarrNaming)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonarrUI) DeepCopyInto(out *SonarrUI) {
	*out = *in
	if in.FirstDayOfWeek != nil {
		in, out := &in.FirstDayOfWeek, &out.FirstDayOfWeek
		*out = new(int)
		**out = **in
	}
	if in.ShowRelativeDates != nil {
		in, out := &in.ShowRelativeDates, &out.ShowRelativeDates
		*out = new(bool)
		**out = **in
	}
	if in.EnableColorImpairedMode != nil {
		in, out := &in.EnableColorImpairedMode, &out.EnableColorImpairedMode
		*out = new(bool)
		**out = **in
	}
	if in.UILanguage != nil {
		in, out := &in.UILanguage, &out.UILanguage
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonarrUI.
func (in *SonarrUI) DeepCopy() *SonarrUI {
	if in == nil {
		return nil
	}
	out := new(SonarrUI)
	in.DeepCopyInto(out)
	return out
}
