//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kyleseneker/media-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrConfig) DeepCopyInto(out *SeerrConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrConfig.
func (in *SeerrConfig) DeepCopy() *SeerrConfig {
	if in == nil {
		return nil
	}
	out := new(SeerrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeerrConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrConfigList) DeepCopyInto(out *SeerrConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeerrConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrConfigList.
func (in *SeerrConfigList) DeepCopy() *SeerrConfigList {
	if in == nil {
		return nil
	}
	out := new(SeerrConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeerrConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrConfigSpec) DeepCopyInto(out *SeerrConfigSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(commonv1alpha1.ReconcileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.JellyfinAuth != nil {
		in, out := &in.JellyfinAuth, &out.JellyfinAuth
		*out = new(SeerrJellyfinAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.PlexAuth != nil {
		in, out := &in.PlexAuth, &out.PlexAuth
		*out = new(SeerrPlexAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.Main != nil {
		in, out := &in.Main, &out.Main
		*out = new(SeerrMain)
		(*in).DeepCopyInto(*out)
	}
	if in.Sonarr != nil {
		in, out := &in.Sonarr, &out.Sonarr
		*out = new(SeerrServiceConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.Radarr != nil {
		in, out := &in.Radarr, &out.Radarr
		*out = new(SeerrServiceConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]SeerrNotificationAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrConfigSpec.
func (in *SeerrConfigSpec) DeepCopy() *SeerrConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SeerrConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrConfigStatus) DeepCopyInto(out *SeerrConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Initialized != nil {
		in, out := &in.Initialized, &out.Initialized
		*out = new(bool)
		**out = **in
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrConfigStatus.
func (in *SeerrConfigStatus) DeepCopy() *SeerrConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SeerrConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrConnection) DeepCopyInto(out *SeerrConnection) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(commonv1alpha1.SecretKeyRef)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(commonv1alpha1.TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrConnection.
func (in *SeerrConnection) DeepCopy() *SeerrConnection {
	if in == nil {
		return nil
	}
	out := new(SeerrConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrJellyfinAuth) DeepCopyInto(out *SeerrJellyfinAuth) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.UseSsl != nil {
		in, out := &in.UseSsl, &out.UseSsl
		*out = new(bool)
		**out = **in
	}
	out.UsernameSecretRef = in.UsernameSecretRef
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrJellyfinAuth.
func (in *SeerrJellyfinAuth) DeepCopy() *SeerrJellyfinAuth {
	if in == nil {
		return nil
	}
	out := new(SeerrJellyfinAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrMain) DeepCopyInto(out *SeerrMain) {
	*out = *in
	if in.HideAvailable != nil {
		in, out := &in.HideAvailable, &out.HideAvailable
		*out = new(bool)
		**out = **in
	}
	if in.LocalLogin != nil {
		in, out := &in.LocalLogin, &out.LocalLogin
		*out = new(bool)
		**out = **in
	}
	if in.MediaServerLogin != nil {
		in, out := &in.MediaServerLogin, &out.MediaServerLogin
		*out = new(bool)
		**out = **in
	}
	if in.DefaultPermissions != nil {
		in, out := &in.DefaultPermissions, &out.DefaultPermissions
		*out = new(int)
		**out = **in
	}
	if in.PartialRequestsEnabled != nil {
		in, out := &in.PartialRequestsEnabled, &out.PartialRequestsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrMain.
func (in *SeerrMain) DeepCopy() *SeerrMain {
	if in == nil {
		return nil
	}
	out := new(SeerrMain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrNotificationAgent) DeepCopyInto(out *SeerrNotificationAgent) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = new(int)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrNotificationAgent.
func (in *SeerrNotificationAgent) DeepCopy() *SeerrNotificationAgent {
	if in == nil {
		return nil
	}
	out := new(SeerrNotificationAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrPlexAuth) DeepCopyInto(out *SeerrPlexAuth) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.UseSsl != nil {
		in, out := &in.UseSsl, &out.UseSsl
		*out = new(bool)
		**out = **in
	}
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrPlexAuth.
func (in *SeerrPlexAuth) DeepCopy() *SeerrPlexAuth {
	if in == nil {
		return nil
	}
	out := new(SeerrPlexAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeerrServiceConnection) DeepCopyInto(out *SeerrServiceConnection) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	out.APIKeySecretRef = in.APIKeySecretRef
	if in.UseSsl != nil {
		in, out := &in.UseSsl, &out.UseSsl
		*out = new(bool)
		**out = **in
	}
	if in.ActiveProfileId != nil {
		in, out := &in.ActiveProfileId, &out.ActiveProfileId
		*out = new(int)
		**out = **in
	}
	if in.Is4k != nil {
		in, out := &in.Is4k, &out.Is4k
		*out = new(bool)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.EnableSeasonFolders != nil {
		in, out := &in.EnableSeasonFolders, &out.EnableSeasonFolders
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeerrServiceConnection.
func (in *SeerrServiceConnection) DeepCopy() *SeerrServiceConnection {
	if in == nil {
		return nil
	}
	out := new(SeerrServiceConnection)
	in.DeepCopyInto(out)
	return out
}
